package session

import (
	"encoding/json"
	"strings"
	"testing"
	"unicode/utf8"
)

func TestTruncateString(t *testing.T) {
	tests := []struct {
		name   string
		in     string
		maxLen int
		want   string
	}{
		{"short string is returned unchanged", "hello", 120, "hello"},
		{"exactly maxLen is not truncated", strings.Repeat("x", 10), 10, strings.Repeat("x", 10)},
		{"long ascii is cut with an ellipsis", strings.Repeat("x", 20), 10, strings.Repeat("x", 7) + "..."},
		{"empty string", "", 120, ""},

		// The limit counts characters, not bytes, so a non-ASCII prompt gets the
		// same amount of text as an ASCII one rather than a third of it.
		{"multi-byte counts as one rune each", strings.Repeat("é", 10), 10, strings.Repeat("é", 10)},
		{"multi-byte is cut by rune", strings.Repeat("日", 20), 10, strings.Repeat("日", 7) + "..."},

		// Guards: the byte-slicing version panicked on maxLen < 3.
		{"zero maxLen", "hello", 0, ""},
		{"negative maxLen", "hello", -5, ""},
		{"maxLen below the ellipsis width", "hello", 2, "he"},
		{"maxLen exactly the ellipsis width", "hello", 3, "hel"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := truncateString(tt.in, tt.maxLen); got != tt.want {
				t.Errorf("truncateString(%q, %d) = %q, want %q", tt.in, tt.maxLen, got, tt.want)
			}
		})
	}
}

// The bug behind #68: slicing by byte split a rune, so a preview of non-ASCII
// text ended in a replacement character.
func TestTruncateStringKeepsValidUTF8(t *testing.T) {
	inputs := map[string]string{
		"cjk":     "a" + strings.Repeat("日", 60),
		"accents": strings.Repeat("é", 80),
		"emoji":   "b" + strings.Repeat("🙂", 40),
		"mixed":   "café " + strings.Repeat("日本語 ", 30),
	}

	for name, in := range inputs {
		t.Run(name, func(t *testing.T) {
			// Sweep lengths so the cut lands at every offset within a rune,
			// rather than only where it happens to align.
			for maxLen := 4; maxLen <= 120; maxLen++ {
				got := truncateString(in, maxLen)
				if !utf8.ValidString(got) {
					t.Fatalf("truncateString(%s, %d) produced invalid UTF-8: %q", name, maxLen, got)
				}
				if n := utf8.RuneCountInString(got); n > maxLen {
					t.Fatalf("truncateString(%s, %d) returned %d runes, want at most %d", name, maxLen, n, maxLen)
				}
			}
		})
	}
}

// userLine builds a JSONL user-turn line with the given content string, the
// shape extractPromptFromLine parses out of real session logs.
func userLine(t *testing.T, content string) string {
	t.Helper()
	encoded, err := json.Marshal(content)
	if err != nil {
		t.Fatalf("marshal content: %v", err)
	}
	return `{"type":"user","message":{"role":"user","content":` + string(encoded) + `}}`
}

func TestExtractPromptFromLine(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    string
	}{
		{
			name:    "plain prompt",
			content: "fix the flaky test in watcher",
			want:    "fix the flaky test in watcher",
		},
		{
			name:    "newlines are decoded, not shown as literal backslash-n",
			content: "first line\nsecond line",
			want:    "first line\nsecond line",
		},
		{
			name:    "quotes and backslashes survive the round trip",
			content: `he said "hi" \ then left`,
			want:    `he said "hi" \ then left`,
		},
		{
			name:    "slash command shows the command, not the wrapper markup",
			content: "<command-name>/model</command-name>\n            <command-message>model</command-message>\n            <command-args></command-args>",
			want:    "/model",
		},
		{
			name:    "command-message may come first",
			content: "<command-message>doctor</command-message>\n<command-name>/doctor</command-name>",
			want:    "/doctor",
		},
		{
			name:    "local-command caveat turn carries no user text",
			content: "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>",
			want:    "",
		},
		{
			// The marker only counts at the start of the turn. Matching it
			// anywhere replaced real prompts that merely mention the markup --
			// observed in the wild on an expanded /doctor prompt, which quotes
			// "<command-name>" in its own instructions.
			name:    "prompt mentioning the markup keeps its own text",
			content: "why does <command-name>/foo</command-name> show up in my history previews?",
			want:    "why does <command-name>/foo</command-name> show up in my history previews?",
		},
		{
			name:    "prompt mentioning the caveat marker is not dropped",
			content: "the preview is blank whenever <local-command-caveat> appears",
			want:    "the preview is blank whenever <local-command-caveat> appears",
		},
		{
			name:    "scaffolding without a parseable command name is skipped",
			content: "<command-args>--verbose</command-args>",
			want:    "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := extractPromptFromLine(userLine(t, tt.content)); got != tt.want {
				t.Errorf("extractPromptFromLine() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestExtractPromptFromLineContentArray(t *testing.T) {
	line := `{"type":"user","message":{"role":"user","content":[{"type":"text","text":"line one\nline two"}]}}`
	if got, want := extractPromptFromLine(line), "line one\nline two"; got != want {
		t.Errorf("extractPromptFromLine() = %q, want %q", got, want)
	}
}

func TestExtractPromptFromLineTruncates(t *testing.T) {
	got := extractPromptFromLine(userLine(t, strings.Repeat("a", 200)))
	if want := strings.Repeat("a", 117) + "..."; got != want {
		t.Errorf("extractPromptFromLine() = %q, want %q", got, want)
	}
}

func TestUnescapeJSONStringFallsBackToRaw(t *testing.T) {
	// A half-written log line can leave extractQuotedValue no closing quote to
	// stop at, so the raw slice is not a decodable JSON string body. Showing
	// the escaped text beats showing nothing.
	const malformed = `unterminated \u00`
	if got := unescapeJSONString(malformed); got != malformed {
		t.Errorf("unescapeJSONString() = %q, want the raw input %q back", got, malformed)
	}
}
